#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc config normal_border_color "#002b36"
bspc config active_border_color "#002b36"
bspc config focused_border_color "#839496"

xinput set-prop 10 289 1
xinput set-prop 10 299 1
xrdb .Xresources
compton -b
redshift &
yabar &
~/.fehbg
