return {
    "nvim-treesitter/nvim-treesitter-refactor",
    { 
        "nvim-treesitter/nvim-treesitter",
        lazy = false,
        build = ":TSUpdate",
        opts = {
            ensure_installed = {
                "c",
                "cmake",
                "cpp",
                "css",
                "dockerfile",
                "glsl",
                "go",
                "gomod",
                "gosum",
                "groovy",
                "haskell",
                "hcl",
                "html",
                "htmldjango",
                "java",
                "javascript",
                "jinja",
                "jinja_inline",
                "json",
                "lua",
                "markdown",
                "markdown_inline",
                "meson",
                "nginx",
                "nix",
                "python",
                "rust",
                "scheme",
                "terraform",
                "toml",
                "typescript",
                "typst",
                "tsx",
                "xml",
                "yaml",
                "zsh",
            },

            highlight = { enable = true },
            indent = { enable = true },
            refactor = {
                highlight_definitions = {
                    enable = true,
                    clear_on_cursor_move = true,
                },
            },
        }},
}
